[package]
name = "plaid-openapi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.17.0", features = ["full"] }
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
httpclient = "0.1"